spring.application.name=marketplace-api

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace-api
spring.datasource.username=root
spring.datasource.password=Dombajecar123$


app.upload.dir=uploads

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dominikspajic7@gmail.com
spring.mail.password=excp boxc ehsr vivx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
