spring.application.name=marketplace-api

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace-api
spring.datasource.username=root
spring.datasource.password=marketplaceapi12345$

app.upload.dir=uploads