spring.application.name=marketplace-api

aws.accessKeyId=AKIAX5DUG2ZPBT7EDDWR
aws.secretKey=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
aws.s3.region=eu-central-1
aws.s3.bucketName=dspajic-marketplace-app-post-images-storage


spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.username=root
spring.datasource.password=Dombajecar123$